### ISSUE TITLE
Fix load-sample-data

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1178]
Check out the steps in https://docs.djangopackages.org/en/latest/install/#load-sample-data

Try to add a new package after running it.

**Comment by ryancheley** [comment]
@jefftriplett when I run it locally I'm seeing two things:

1. There's a message about an unapplied migration, but when I try to run the migration I get the error `relation "profiles_extrafield" already exists`. The app runs locally without issue though 🤷 
2. When I try to add a package in the admin I get a primary key constraint error `duplicate key value violates unique constraint "package_package_pkey"
DETAIL:  Key (id)=(1) already exists.`
3. The same error happens when I try to add a package through the front end

I am able to get the package to be added (either in the frontend or the admin) IF I try and add it a few times

I think the root of the issue is that test data has the PKs 1, 2, 3, 4, 6, 7, 8. This means that I need to keep adding a package until I get to PK 5 (which will be added without issue) and then I need to add a package three more times after that to get the PK to 9 for it to be added without issue

**Comment by saadmk11** [comment]
> I think the root of the issue is that test data has the PKs 1, 2, 3, 4, 6, 7, 8.

Yes, this seems to be the issue.

But the way this project and the it's tests are structured just removing the `pk` fields when creating the objects (on `load()` method will not work. e.g:

```diff
package1, created = Package.objects.get_or_create(
-   pk=1,
    category=category,
    repo_watchers=0,
    title="Testability",
)
```

Because this will break most of the tests as they heavily rely on the `pk`s of those objects. e.g:

https://github.com/djangopackages/djangopackages/blob/71038637178c45f6f06c7fc6c9c47e6ea46f4541/grid/tests/test_views.py#L340-L349
