### ISSUE TITLE
🖼️  Convert "Filter results" to an inline style on the grid detail page

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#1187]
Please take a look at this screenshot. We should update the styles/layout on the "Filter results" feature: 

![Xnapper-2024-07-01-21 43 31-58066F76-1DFB-4D5D-8BFB-B2655D492061](https://github.com/djangopackages/djangopackages/assets/50527/89635eed-d7c8-4122-aa54-cdaea16a608c)

See: https://djangopackages.org/grids/g/components/

The template code is here: https://github.com/djangopackages/djangopackages/blob/b396949e5f36037baa0cf0e00a4c80319926d9da/templates/grid/grid_detail.html#L45-L49

**Comment by jefftriplett** [comment]
@lipemorais this might be a good first-time issue if you want to tackle it?

**Comment by lipemorais** [comment]
Sure! I can help with it.

**Comment by lipemorais** [comment]
Hi, @jefftriplett ! I started to look at this issue today, but I'm not clear on how to do it; my CSS is pretty basic. I see the row class has already been applied to the div. I know that I should use something like a `style="display:inline-block"` but  my attempts have failed to see any change in the style of these components, I also tried to use the `d-inline` from bootstrap but no success as well.

I'm testing it on the link you shared because I don't have grids in my local environment working as expected. Not sure if I should have it working by now. If yes, could provide me some instructions to make it work?
![image](https://github.com/djangopackages/djangopackages/assets/5021565/b038394b-fa35-4981-8938-f169a1b87632)


Would you happen to have an example of how it should look like?
1. The options should be on the same line of filter results
2. the options and the sort by should be on the same line.

**Comment by jefftriplett** [comment]
@lipemorais 

I would double-check that you have data and have run `python -m manage load_dev_data` which will setup a few packages for you

Next, I would create a Grid and add a few of these Packages to the Grid.  

You should be able to use this newly create Grid to see the form and test options. 

(I thought we already set up a Grid by default, but I just ran it and I'm not seeing one. I can update it later tonight, but I'm an hour into an nine-hour drive)

**Comment by jefftriplett** [comment]
I'm seeing http://localhost:8000/grids/g/testing/ setup as a default grid with four packages in it. You might try that and see if it works for you.

**Comment by lipemorais** [comment]
Hey, @jefftriplett!

Thanks, I'm able to setup it locally now but there was a important piece you missed in my message above.

I want to know what exactly should be inline; I gave a few options on it.

Here is a print screen of the comment I sent above
![image](https://github.com/djangopackages/djangopackages/assets/5021565/500aa993-9b0d-4a6d-8e05-f2cbb9ffefc0)

**Comment by lipemorais** [comment]
I may have found the solution. Is it the expected result?

![image](https://github.com/djangopackages/djangopackages/assets/5021565/c6fa7cde-db67-4772-b8e7-989b11d67962)

**Comment by jefftriplett** [comment]
Hi @lipemorais, I had seem them but was traveling and wasn't in a good place to take a screenshot. 

I think what you landed on is good and 90% there.  I would try the parent div to example to the width of the page. Something like changing:

```html
<div class="col-lg-2 col-md-3 col-sm-4">
```

To:

```html
<div class="col-lg-12 col-md-12 col-sm-12">
```

That should help the sort by bubble up to the same line.

**Comment by lipemorais** [comment]
Thanks! I will try that

**Comment by lipemorais** [comment]
I implemented it the way you suggested, @jefftriplett,  but it looks a bit strange to me.

Large screen
<img width="543" alt="image" src="https://github.com/djangopackages/djangopackages/assets/5021565/5c7402d0-44b9-49d3-9478-54cb3ccaf899">

Small screen
<img width="630" alt="image" src="https://github.com/djangopackages/djangopackages/assets/5021565/ff05982c-4003-4bba-ab1a-38df255e99c6">

**Comment by jefftriplett** [comment]
@lipemorais please push this last template change, and we can complete it. I can update the form to use the form fields individually and skip having crispy forms process it all. (goal is a quick win for you not to create a never-ending issue)
