### ISSUE TITLE
Rate limiting broken?

### ISSUE THREAD

**Issue by benebun** [djangopackages/djangopackages#494]
I read in [this issue comment](https://github.com/djangopackages/djangopackages/issues/485#issuecomment-328275359) that the rate limiting is 2 per second.

I'm not sure if this is working as expected because I reach this limit just by opening https://djangopackages.org/ and submitting a search e.g. https://djangopackages.org/search/?q=shop and get the "429 Too Many Requests" error which is certainly not within the same second.
If that's not broken maybe an increase might be considered so the page can be used "normally"?
Thanks!

**Comment by jayfk** [comment]
We're still having problems with people hammering the API, that's why the rate limit is necessary.

I believe the search is submitting a request on every keystroke and thus running into the rate limit.

Gone up with the rate limit here (7 per second with an additional burst of 3 per second): https://github.com/djangopackages/djangopackages/commit/4d3b92a79cc164374fdff71384075df368289e82

**Comment by benebun** [comment]
Gnargh hit this again because I'm not expecting the on the fly search results esp. outside of the input field so I hit enter after typing to submit the search :\ But at least I know why now…

**Comment by jayfk** [comment]
Dargh, that's horrible. I'm going to remove the ratelimit for now. Let's see how that goes.
