### ISSUE TITLE
🤖  Automate Changelog Updates

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#688]
I'd like to add a Changelog and section to the website so that it's easier to see what's changing. 

I noticed that Cookiecutter Django is doing some shiny things: https://github.com/pydanny/cookiecutter-django/blob/master/.github/workflows/update-changelog.yml

**Comment by r-lelis** [comment]
I'm gonna work on this one if that's ok. @jefftriplett

**Comment by jefftriplett** [comment]
Sounds great. 👍

**Comment by sabderemane** [comment]
Hi @jefftriplett , I think this issue is resolved according [this file](https://github.com/djangopackages/djangopackages/blob/main/.github/changelog-template.md).

Do you think it will be useful to add an action which will close issue when the PR is merged on the main branch ? I can implement that if needed, I have seen this [action](https://github.com/ldez/gha-mjolnir) which can be nice.

**Comment by jefftriplett** [comment]
@sabderemane I'm not against better automation, but this was probably my fault for not adding a `fixes #{number}`  when the pull request was merged. 

That said, I'm +1 looking at our process and making it tidier. Same for what our PR/new issue requirements since I haven't had time to spend much time looking at those. They might be good #hacktoberfet issues too.

**Comment by jefftriplett** [comment]
Free to open a new discussion or issue and we can continue the discussion. I'll clean up issues that should already be closed.
