### ISSUE TITLE
Packages with custom git repos are not being scored

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#850]
See this tweet: https://twitter.com/morenoh149/status/1580971411145125888

Package scoring should factor in packages that exist on PyPI, but might have a custom repo location. They appear to be scored as a 0 and won't show up in Grids.

**Comment by saadmk11** [comment]
I took a quick peek at this. It seems like the `Package.calculate_score()` method returns `0` if the `Package.repo_watchers` field is set to `0`.
https://github.com/djangopackages/djangopackages/blob/9951ae1f3ceff06e37af1e2c413dfc1e5552317d/package/models.py#L394-L416

And the `grid_detail` view is filtering out the packages that score `<1`. (This makes the package not show up in the grid)
https://github.com/djangopackages/djangopackages/blob/9951ae1f3ceff06e37af1e2c413dfc1e5552317d/grid/views.py#L306-L308

This happens when the `UnsupportedHandler` (Unsupported Git Service) is used.

https://github.com/djangopackages/djangopackages/blob/9951ae1f3ceff06e37af1e2c413dfc1e5552317d/package/repos/unsupported.py#L11

A quick fix would be to either update the `Package.calculate_score()` method to use the value `1` for `repo_watchers` if `Package.repo_watchers` field is set to `0` or set a default for `Package.repo_watchers` in the `UnsupportedHandler`

**Comment by jefftriplett** [comment]
Thank you @saadmk11 for the assist. 

I added a quick fix and will circle back on a better fix.
