### ISSUE TITLE
:tractor: Upgrade DO Box

### ISSUE THREAD

**Issue by jefftriplett** [djangopackages/djangopackages#876]
I think our server is a bit overdue to upgrade/swap out. Our DB is running on a managed instance so that takes some of the edge off of swapping things out. 

<img width="837" alt="Xnapper-2022-11-13-10 44 27-64F5977F-9B3A-4C83-8EBD-3EEFA3C71831" src="https://user-images.githubusercontent.com/50527/201533520-fdb981c1-42a4-4fee-8d38-c4c353885d80.png">

Incomplete steps: 

- [x] Spin up a new droplet
- [x] Install/configure Docker
- [x] Test against our image
- [x] Configure/test Docker to restart on boot
- [x] Test Caddyserver
- [x] Test cron jobs
- [x] Update Fabric deploy
- [x] Test rebooting 

This is probably a good time to switch to having Docker images built on GitHub instead of making that part of the fabric deploy process. We can either run something like [Watchtower](https://github.com/containrrr/watchtower) or modify our existing fabric system to pull images since it's a pretty decent blue/green deploy system.

**Comment by saadmk11** [comment]
This looks interesting, DO also has their new app platform (probably bit more expensive then regular droplets) that automates deployment for containers. https://docs.digitalocean.com/products/app-platform/

**Comment by ryancheley** [comment]
I’d be super interested to help with this.

**Comment by saadmk11** [comment]
Me too! 😃

**Comment by jefftriplett** [comment]
I'm getting ready to hop on this. Curious about what y'all are interested in and what would be helpful. 

I'll probably start on the top bullet list and start adding things to that as they come up.

**Comment by ryancheley** [comment]
@jefftriplett kind of the entire process honestly. My experience with deploying to Digital Ocean has been small hobby projects that don’t use docker. Even at work we’re not using docker, so it’s not something I have any experience with in a production setting, but would like to have more practical hands on experience with. 

I’ve also never used Caddyserver (but do have a bit of working knowledge of nginx which seems like it may be helpful 🤷🏼‍♂️) or Fabric, but would be interested in learning more about both.

**Comment by saadmk11** [comment]
I am interested in Caddy server which I have not used before and the whole deployment automation process with DO. :). I have some experience with deploying with Docker in Droplets and EC2 instances.

**Comment by luzfcb** [comment]
@jefftriplett I recently implemented continuous deploy with docker compose + github Packages (as host for docker images) + caddy server (latest version) + digital ocean. Let me know if you need any help.

**Comment by jefftriplett** [comment]
@luzfcb sounds great. My main mental blocker has been making the blue/green deploys work smoothly. Is that something you have dealt with?

**Comment by luzfcb** [comment]
> making the blue/green deploys work smoothly. Is that something you have dealt with?

Yes, in parts (because I haven't implemented an automated rollback routine).

I was greatly inspired by the things done in djangopackages, although the end result of the configurations is quite different.


The changes I made regarding djangopackages' blue/green implementation were that:
- I don't use docker compose to compile the docker images on Digital Ocean. I have a custom script that does this for me locally and on Github Actions and that uses docker build with some extra arguments  (like including the git commit hash value an environment var APPLICATION_VERSION the docker image)
- The docker image (along with backend and frontend compiled source code) is built in a Github Action and uploaded to Github Packages
- I have implemented a docker health check for all docker services
- Docker compose only references the image in github packages, and I basically run `docker compose pull django-a` + `docker compose up -d --wait`
- for docker on DO to have access to Github packages, we need to create another github account (to work as machine account) and [create a CLASSIC personal github token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-personal-access-token-classic) with the "read:packages" permission : https://github.com/settings/tokens/new?scopes=read:packages 

```bash
    GH_TOKEN="<TOKEN_HASH>"
    echo "${GH_TOKEN}" | docker login ghcr.io -u "${GH_USER}" --password-stdin
```

If django-a's health check never reports the `healthy` state to docker, then django-b will never get updated because the script will timeout and the deploy process will return a fail status
