### ISSUE TITLE
Duplicate Entry for Django Haystack

### ISSUE THREAD

**Issue by udit-001** [djangopackages/djangopackages#881]
**Describe the bug**
Django Haystack has got duplicate entries:
- https://djangopackages.org/packages/p/django-haystack1/ : This has the correct repository link
- https://djangopackages.org/packages/p/django-haystack/ : This has incorrect repository link, also I noticed that the section "Sites using this package" contains suspicious links 👀 

**To Reproduce**
1. Visit the links mentioned

**Expected Behaviour**
Delete the duplicate entry.

**Comment by jefftriplett** [comment]
Thank you for this report. This is semi-fixed. 

Toastdriven was the original author and later created a GitHub org for the project before later creating a fork of the project which ironically matched the packages's original URL

- I updated the OG link (package #23) to point to the updated repo
- I deleted the duplicated package
- I disabled the spammy websites
- I created a new ticket to address spammy websites since this is a big problem. 
- I gave @ryancheley admin access (you should see an "Admin" url at the top of the page, so you can see more.

**Comment by jefftriplett** [comment]
> * also I noticed that the section "Sites using this package" contains suspicious links 👀
