### ISSUE TITLE
Cache invalidation rarely triggered

### ISSUE THREAD

**Issue by fabien-michel** [djangopackages/djangopackages#893]
**Describe the bug**
Adding a package to grid, adding a feature, editing package feature status does not invalidate grid page cache.
This made editing difficult. (eg. 🤔 Did my action have an effect ?)

**Expected behavior**
Page should instantly display modifications applied

**Comment by saadmk11** [comment]
This probably happens because the grid detail page uses template caching.

https://github.com/djangopackages/djangopackages/blob/e13f9fb55ae21a9013fdfc67bdbe1297d226a86a/templates/grid/grid_detail.html#L42

The template is cached for every 10 minutes.

**Comment by jefftriplett** [comment]
Thank you for this feedback. This has been on my mind to fix for a while, but we haven't quite gotten to it yet. We just added a bunch of metadata to help build a more accurate picture of where packages are, so I think we are close to refactoring how features work and what a better balance is because updating the grids is both a pain to update and to maintain.

**Comment by jefftriplett** [comment]
I have been running this by hand, but it's supported in fabric via:

https://github.com/djangopackages/djangopackages/blob/main/fabfile.py#L155-L158

Ideally, this would be automated, but there are a few blockers like #893
